### ISSUE TITLE
Can support other mmWave module?

### ISSUE THREAD

**Issue by KirkLin16** [vilari-mickopf/mmwave-gesture-recognition#1]
Hi

Thank you for public this amazing project. I want to follow your work, but I don't have AWR1642. I have AWR1843 and IWR6843 in hand. How I can use these two modules to run your project? Appreciate your contribution!

Best Regard!
Kirk

**Comment by vilari-mickopf** [comment]
Python stuff should work just fine, but you will need different fw compiled for your boards. I've used mmwave demo 2.0.0.4, which can detect (x,y) position of points, that I'm later using for training/prediction. I'm not so sure how much the demo is different for other boards (if at all). If there is any difference, you can modify formats [here](https://github.com/vilari-mickopf/mmwave-gesture-recognition/blob/5b4a69a64e77988dc959c97fb34ccb7274bccba6/mmwave/data/formats.py#L172) and [here](https://github.com/vilari-mickopf/mmwave-gesture-recognition/blob/5b4a69a64e77988dc959c97fb34ccb7274bccba6/mmwave/data/formats.py#L236). Parser module is taking these formats descriptions and it creates a dict of parsed data that is formatted in the same way as formats dict. The only point of interest for prediciton is [objs](https://github.com/vilari-mickopf/mmwave-gesture-recognition/blob/5b4a69a64e77988dc959c97fb34ccb7274bccba6/mmwave/data/formats.py#L178) with `range_idx`, `doppler_idx`, `peak_value`, `x_coord` and `y_coord`  (`z_coord` is always zero for me, because of antennas on 1642).

**Comment by vilari-mickopf** [comment]
Also, you should modify [profile.cfg](https://github.com/vilari-mickopf/mmwave-gesture-recognition/blob/master/mmwave/communication/profiles/profile.cfg) file to support your board.

**Comment by KirkLin16** [comment]
Thank you very much for your reply. I check out the doxygen file of the new version SDK(03.05.00.04) and the format of detect object for 1843,6843 and even 1642 are changed as below. 
![image](https://user-images.githubusercontent.com/86407178/133188427-2f780592-3bd7-4040-879d-1f06adf659a2.png)

 Since the data format for prediction are also changed, is that mean I need to change a big part of your code?

And the TLV structure is also change to:
![image](https://user-images.githubusercontent.com/86407178/133203766-41d421be-b5e7-4ba1-b1aa-0485f5b24b68.png)
compare to former one:
![image](https://user-images.githubusercontent.com/86407178/133203839-fd499134-b3d0-49f6-ab50-afd0131cbb35.png)

Thanks again!
Kirk

**Comment by vilari-mickopf** [comment]
Hmm, you should modify few stuff, not much really, but you will need to record new set of data. First you should modify formats of objs as explained, then you should modify [what is being logged](https://github.com/vilari-mickopf/mmwave-gesture-recognition/blob/5b4a69a64e77988dc959c97fb34ccb7274bccba6/mmwave/data/logger.py#L57) on log command. Now your data is different, so [reading](https://github.com/vilari-mickopf/mmwave-gesture-recognition/blob/5b4a69a64e77988dc959c97fb34ccb7274bccba6/mmwave/data/logger.py#L127) should be modified as well. And [number of objs in your data](https://github.com/vilari-mickopf/mmwave-gesture-recognition/blob/5b4a69a64e77988dc959c97fb34ccb7274bccba6/mmwave/model.py#L40) is now 4 (if you are using x, y, z and velocity) instead of 5 (x, y, doppler, peak and range in mine). Models should work just fine with one column less, maybe even better, beacuse velocity is probably better feature than doppler idx, peak idx and range idx. You will need to retrain them with train command ofc. I've used clutter removal to remove all static points, so I would advise to keep that on when recording new data.
And that's it, I think that should do the job.

**Comment by KirkLin16** [comment]
Thank you so much for your help. I will try as you advised.

**Comment by vilari-mickopf** [comment]
If you have more questions, feel free to reopen the issue.
