### ISSUE TITLE
Testing Environment

### ISSUE THREAD

**Issue by kanybekasanbekov** [vilari-mickopf/mmwave-gesture-recognition#3]
Hi,       
I have some problems when testing the project. I have checked the accuracy of models, all of them achieve 99%. However, during real testing model fails to correctly recognize my gestures. Could you please make a short video showing your testing environment and show how one should move hands to properly recognize gestures?

Thanks.

**Comment by vilari-mickopf** [comment]
Whole data set was created using only my gestures, so models are probably overfitted to me, and it does work just fine in real testing for me. You can always record your own gestures and retrain models with them.

Here is my footage: https://drive.google.com/file/d/1jLj6-0hzaesZALlGzwi1y7zK2rP7z5Pg/view?usp=sharing
(_I've used wide lens in order to be able to record with my left hand and do the gestures with the right one, so the gestures may look bigger than what they are. You can follow the plotter for some reference tho_)

**Comment by kanybekasanbekov** [comment]
Thank you so much for the video. Our setup was completely different, that's why the model was not able to recognize gestures. I would suggest you put a video(or GIF) like above in README.md so that people can easily understand.

**Comment by kanybekasanbekov** [comment]
I have one more question about radar setup. In the video above I have noticed that jumpers P5, P7 were closed and something Red&Yellow placed around SOP jumpers. Does this setting effect the received signals? Could you please take picture of the radar and show it? Thank you.
![radaar](https://user-images.githubusercontent.com/34956058/135216803-61e21ab9-4251-4fd2-abdb-70127870ca0c.jpg)

**Comment by vilari-mickopf** [comment]
I'm just really bad at saving my jumpers, so I always keep them like this :)![PXL_20210929_152204906.jpg](https://user-images.githubusercontent.com/39714069/135278059-65ee242c-de4e-42c1-ae82-8074a164065e.jpg)
![PXL_20210929_152139298.jpg](https://user-images.githubusercontent.com/39714069/135278181-e92ad718-f780-4b4d-a6e3-1060eccdd88e.jpg)
